// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8GC6M9Tkxew8tFR_u4TmMHmhHxzNgcI',
    appId: '1:511985847427:web:b704f17facfbea1a361fb6',
    messagingSenderId: '511985847427',
    projectId: 'shopease2025-6c81d',
    authDomain: 'shopease2025-6c81d.firebaseapp.com',
    storageBucket: 'shopease2025-6c81d.firebasestorage.app',
    measurementId: 'G-989BLT74V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoa9NYQ-5TFLIEqtCjeK7Wz_ECu1AOslw',
    appId: '1:511985847427:android:0f92cd81533b6991361fb6',
    messagingSenderId: '511985847427',
    projectId: 'shopease2025-6c81d',
    storageBucket: 'shopease2025-6c81d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhA1BIEKnuzWp7GSdkVaIojmnnknJQxOQ',
    appId: '1:511985847427:ios:947fff2f9c94ee41361fb6',
    messagingSenderId: '511985847427',
    projectId: 'shopease2025-6c81d',
    storageBucket: 'shopease2025-6c81d.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );
}
